#!/usr/bin/with-contenv sh

# Master admin email must be informed
if [ -z "$DASPANEL_MASTER_EMAIL" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_MASTER_EMAIL to a valid email"
    echo "***"
    exit 1
fi

# unless this has already been defined
if [ -z "$DASPANEL_MASTER_PASSWORD" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_MASTER_PASSWOR"
    echo "***"
    exit 1
fi

# unless this has already been defined
if [ -z "$DASPANEL_GUUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_GUUID"
    echo "***"
    exit 1
fi
